---
- hosts: nova
  become: true
  tasks:
  - name: install packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - nova-compute

  - name: count the cpu register
    shell: "grep -c '(vmx|svm)' /proc/cpuinfo || true "
    register: cpu_count

  - name: /etc/nova/nova.conf  configuration template
    template:
      src: nova.conf.j2
      dest: /etc/nova/nova.conf
      owner: root
      group: nova
      mode: 0640

  # networking configuration
  - name: neutron-linuxbridge-agent packate install
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - neutron-linuxbridge-agent

  - name: /etc/neutron/neutron.conf configuration template
    template:
      src: neutron.conf.j2
      dest: /etc/neutron/neutron.conf
      owner: root
      group: neutron
      mode: 0640

  - name: /etc/neutron/plugins/ml2/linuxbridge_agent.ini template file
    template:
      src: linuxbridge_agent.ini.j2
      dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
      owner: root
      group: neutron
      mode: 0640

  - name: sysctl configuration
    copy:
      src: neutron-sysctl.conf
      dest: /etc/sysctl.d/neutron.conf
      owner: root
      group: root
      mode: 0644
    notify: sysctl reload

  - name: neutron-linuxbridge-agent service up
    service:
      name: neutron-linuxbridge-agent
      state: started
      enabled: true

  - name:  nova-computeb service up
    service:
      name: nova-compute
      state: started
      enabled: true

  handlers:
  - name: sysctl reload
    shell: 'sysctl -p'
